"""empty message

Revision ID: 595cb1abc4d3
Revises: f887b13bc5c9
Create Date: 2023-06-07 15:57:07.985952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '595cb1abc4d3'
down_revision = 'f887b13bc5c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operacao', sa.Column('conta_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'operacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operacao', type_='foreignkey')
    op.drop_column('operacao', 'conta_id')
    # ### end Alembic commands ###
