"""empty message

Revision ID: f887b13bc5c9
Revises: 2b2601a43b73
Create Date: 2023-06-06 16:02:39.518374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f887b13bc5c9'
down_revision = '2b2601a43b73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('operacao_ibfk_1', 'operacao', type_='foreignkey')
    op.drop_column('operacao', 'conta_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operacao', sa.Column('conta_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('operacao_ibfk_1', 'operacao', 'conta', ['conta_id'], ['id'])
    # ### end Alembic commands ###
